---

- name: Check if influxdb datasource configured
  uri:
    method: GET
    user: "{{ grafana_admin_user|quote }}"
    password: "{{ grafana_admin_password|quote }}"
    force_basic_auth: true
    body_format: json
    url: "http://localhost:{{ grafana_port }}/api/datasources"
  register: datasources

- name: Set fact based on influxdb datasource configuration
  set_fact:
    influxdb_datasource_configuration: "{{ datasources.json | selectattr('name', 'equalto', grafana_influxdb_datasource_name) | list }}"

- name: Configure influxdb datasource
  uri:
    method: POST
    user: "{{ grafana_admin_user|quote }}"
    password: "{{ grafana_admin_password|quote }}"
    force_basic_auth: true
    body_format: json
    body: {
      "name": "{{ grafana_influxdb_datasource_name }}",
      "type": "influxdb",
      "url": "http://localhost:8086",
      "access": "proxy",
      "basicAuth": false,
      "database": "collectd",
      "user": "{{ grafana_influxdb_user }}",
      "password": "{{ grafana_influxdb_password }}",
      "isDefault": true
    }
    url: "http://localhost:{{ grafana_port }}/api/datasources"
  when: not influxdb_datasource_configuration

