---
- name: Enable Yum repository
  yum_repository:
    name: grafana
    description: Grafana upstream yum repo
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"

- name: Import RPM key
  rpm_key:
    key: "{{ grafana_repo_key }}"
    state: present

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ grafana_packages }}"
  register: install_packages

- name: Enable and (re)start service
  service:
    name: grafana-server
    enabled: yes
    state: restarted
    use: systemd
  when: install_packages.changed
  tags:
    # ansible-lint wants me to use a handler instead of a task with 'when:
    # something.changed' (ANSIBLE0016). When I did it that way, I needed 'meta:
    # flush_handlers' which is more confusing than the 'when:
    # something.changed' form, so I'm using that form and disabling linting of
    # this play.
    - skip_ansible_lint

- name: Fetch getdash.js
  git:
    repo: "{{ grafana_getdash_js_repo }}"
    version: "{{ grafana_getdash_js_sha }}"
    dest: "{{ grafana_getdash_js_dest }}"
    # getdash.js recomments depth=1 but git in centos7.3 is "too old to fully support the depth argument."
  notify:
    - install getdash.js

- name: Wait for grafana to start
  wait_for:
    port: "{{ grafana_port }}"
