---
- name: Enable Yum repository
  yum_repository:
    name: grafana
    description: Grafana upstream yum repo
    baseurl: "{{ grafana_repo }}"
    gpgcheck: yes
    gpgkey: "{{ grafana_repo_key }}"

- name: Import RPM key
  rpm_key:
    key: "{{ grafana_repo_key }}"
    state: present

- name: Install packages
  package:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ grafana_packages }}"
  notify:
    - restart grafana

- name: Fetch getdash.js
  git:
    repo: "{{ grafana_getdash_js_repo }}"
    version: "{{ grafana_getdash_js_sha }}"
    dest: "{{ grafana_getdash_js_dest }}"
    # getdash.js recomments depth=1 but git in centos7.3 is "too old to fully support the depth argument."
  notify:
    - install getdash.js
